before_script:
  - export JAVA_HOME=/usr/lib/jvm/jdk-18/

variables:
  STG_POINTING_BRANCH: "staging"
  STG_DOCKER_REGISTRY: local/ga-vendor-api-service
  STG_PORTAINER_NAME: game-aggregator_ga-vendor-api-service
  STG_SERVER: ubuntu@ec2-43-198-83-19.ap-east-1.compute.amazonaws.com
  STG_FOLDER_PATH: /home/ubuntu/game_aggregator/ga-vendor-api-service
  STG_MVN: /home/ubuntu/apache_maven/bin/mvn

  QA_POINTING_BRANCH: "qa"
  QA_DOCKER_REGISTRY: esportsking/ga-vendor-api-service
  QA_PORTAINER_NAME: game-aggregator_ga-vendor-api-service
  QA_SERVER: root@47.254.202.80

stages:
  - pull-git
  - build
  - push-img
  - deploy

.stg-deploy-rule:
  rules:
    - if: $CI_COMMIT_BRANCH == $STG_POINTING_BRANCH
  script:
    - echo "$CD_AWS_PRIVATE_KEY" > "$(pwd)/stg-key.pem"
    - chmod 400 "$(pwd)/stg-key.pem"

.qa-deploy-rule:
  rules:
    - if: $CI_COMMIT_BRANCH == $QA_POINTING_BRANCH

stg-aws-pull-git:
  stage: pull-git
  extends: .stg-deploy-rule
  script:
    - ssh -t -oStrictHostKeyChecking=no -i "$(pwd)/stg-key.pem" $STG_SERVER -p 22 "cd $STG_FOLDER_PATH && git fetch --all && git checkout staging && git reset --hard origin/staging"

stg-aws-build:
  stage: build
  needs: ["stg-aws-pull-git"]
  extends: .stg-deploy-rule
  script:
    - ssh -t -oStrictHostKeyChecking=no -i "$(pwd)/stg-key.pem" $STG_SERVER -p 22 "cd $STG_FOLDER_PATH && $STG_MVN clean package -DskipTests=true && docker build -t $STG_DOCKER_REGISTRY:latest $STG_FOLDER_PATH"

stg-aws-deploy:
  stage: deploy
  needs: ["stg-aws-build"]
  extends: .stg-deploy-rule
  script:
    - ssh -t -oStrictHostKeyChecking=no -i "$(pwd)/stg-key.pem" $STG_SERVER -p 22 "docker service update --force --image $STG_POINTING_BRANCH:latest $STG_PORTAINER_NAME"

qa-gitlab-build:
  stage: build
  extends: .qa-deploy-rule
  script:
    - "mvn clean deploy -s ./ci_setting.xml -DskipTests=true"
  artifacts:
    paths:
      - ./target/*.jar

qa-push-dockerhub:
  stage: push-img
  needs: ["qa-gitlab-build"]
  extends: .qa-deploy-rule
  script:
    - docker build -t $QA_DOCKER_REGISTRY:latest .
    - docker login --username=esportsking --password="$DOCKERHUB_PWD"
    - docker push $QA_DOCKER_REGISTRY:latest

qa-ali-deploy:
  stage: deploy
  needs: ["qa-push-dockerhub"]
  extends: .qa-deploy-rule
  script:
    - echo "$CD_PRIVATE_KEY" > "$(pwd)/qa-key.pem"
    - chmod 400 "$(pwd)/qa-key.pem"
    - ssh -t -oStrictHostKeyChecking=no -i "$(pwd)/qa-key.pem" $QA_SERVER -p 22 "docker pull $QA_DOCKER_REGISTRY:latest && docker service update --force --image $QA_DOCKER_REGISTRY:latest $QA_PORTAINER_NAME"
