<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.7.5</version>
		<relativePath/>
		<!-- lookup parent from repository -->
	</parent>

	<groupId>com.nextgen.game-aggregator</groupId>
	<artifactId>game-aggregator-vendor-api-service</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>game-aggregator-vendor-api-service</name>
	<description>game aggregator vendor api service</description>

	<properties>
		<spring-cloud.version>2021.0.5</spring-cloud.version>
		<java.version>18</java.version>
		<javax.version>2.0.1.Final</javax.version>
		<hibernate-validator.version>6.0.13.Final</hibernate-validator.version>
		<glassfish.version>3.0.0</glassfish.version>
		<logstash.version>7.2</logstash.version>
		<nextgen-core.version>2.0.37</nextgen-core.version>
		<java-client.version>3.4.4</java-client.version>
		<projectlombok.version>1.18.24</projectlombok.version>
		<spring-kafka.version>2.9.2</spring-kafka.version>
		<kafka.version>3.3.1</kafka.version>
		<commons-codec.version>1.15</commons-codec.version>
		<netty.version>4.1.86.Final</netty.version>
		<mariadb.version>3.0.8</mariadb.version>
		<poi.version>4.1.2</poi.version>
		<maven.compiler.source>18</maven.compiler.source>
		<maven.compiler.target>18</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<timestamp>${maven.build.timestamp}</timestamp>
		<maven.build.timestamp.format>yyyy-MM-dd HH:mm:ss</maven.build.timestamp.format>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-rest</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-redis</artifactId>
		</dependency>

		<dependency>
			<groupId>javax.validation</groupId>
			<artifactId>validation-api</artifactId>
			<version>${javax.version}</version>
		</dependency>

		<dependency>
			<groupId>org.hibernate.validator</groupId>
			<artifactId>hibernate-validator</artifactId>
			<version>${hibernate-validator.version}</version>
		</dependency>

		<dependency>
			<groupId>org.glassfish</groupId>
			<artifactId>javax.el</artifactId>
			<version>${glassfish.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-dependencies</artifactId>
			<version>${spring-cloud.version}</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>

		<dependency>
			<groupId>net.logstash.logback</groupId>
			<artifactId>logstash-logback-encoder</artifactId>
			<version>${logstash.version}</version>
		</dependency>

		<dependency>
			<groupId>com.nextgen.sas</groupId>
			<artifactId>core</artifactId>
			<version>${nextgen-core.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-security</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.mariadb.jdbc</groupId>
			<artifactId>mariadb-java-client</artifactId>
			<scope>runtime</scope>
			<version>${mariadb.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-couchbase</artifactId>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>${projectlombok.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.kafka</groupId>
			<artifactId>spring-kafka</artifactId>
			<version>${spring-kafka.version}</version>
		</dependency>

		<dependency>
			<groupId>org.apache.kafka</groupId>
			<artifactId>kafka-clients</artifactId>
			<version>${kafka.version}</version>
		</dependency>

		<dependency>
			<groupId>org.apache.kafka</groupId>
			<artifactId>kafka-streams</artifactId>
			<version>${kafka.version}</version>
		</dependency>

		<dependency>
			<groupId>commons-codec</groupId>
			<artifactId>commons-codec</artifactId>
			<version>${commons-codec.version}</version>
		</dependency>

		<!-- Support for Apple M1 chip -->
		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-resolver-dns-native-macos</artifactId>
			<version>${netty.version}</version>
			<classifier>osx-aarch_64</classifier>
		</dependency>

		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>${poi.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>${poi.version}</version>
		</dependency>

		<!--need remove when go live -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
		</dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <!--grpc -->
		<!--		<dependency>-->
		<!--			<groupId>com.nextgen.game-aggregator</groupId>-->
		<!--			<artifactId>game-aggregator-vendor-operator-grpc-proto</artifactId>-->
		<!--			<version>0.0.1-SNAPSHOT</version>-->
		<!--		</dependency>-->
		<!--		<dependency>-->
		<!--			<groupId>net.devh</groupId>-->
		<!--			<artifactId>grpc-client-spring-boot-starter</artifactId>-->
		<!--			<version>2.13.1.RELEASE</version>-->
		<!--		</dependency>-->
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

	<repositories>
		<repository>
			<id>gitlab-maven</id>
			<url>http://223.25.67.48/api/v4/projects/10/packages/maven</url>
		</repository>
		<repository>
			<id>gitlab-maven-2</id>
			<url>http://223.25.67.48/api/v4/projects/41/packages/maven</url>
		</repository>
		<repository>
			<id>gitlab-maven-3</id>
			<url>http://223.25.67.48/api/v4/projects/19/packages/maven</url>
		</repository>
	</repositories>

	<distributionManagement>
		<repository>
			<id>gitlab-maven</id>
			<url>http://223.25.67.48/api/v4/projects/19/packages/maven</url>
		</repository>
		<snapshotRepository>
			<id>gitlab-maven</id>
			<url>http://223.25.67.48/api/v4/projects/19/packages/maven</url>
		</snapshotRepository>
	</distributionManagement>
</project>
