is-test-env=true

spring.data.redis.database=0
spring.data.redis.host=exampleValue
spring.data.redis.username=
spring.data.redis.password=exampleValue
spring.data.redis.protocol=redis

spring.datasource.maria-default.jdbc-url=jdbc:mysql://exampleValue:3306/game_aggregator_qa?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
spring.datasource.maria-default.username=exampleValue
spring.datasource.maria-default.password=exampleValue
spring.datasource.maria-default.driver-class-name=com.mysql.cj.jdbc.Driver

spring.couchbase.connectionString=couchbases://exampleValue
spring.couchbase.userName=exampleValue
spring.couchbase.password=exampleValue
spring.couchbase.bucketName=game_aggregator_qa
spring.couchbase.scopeName=raw

vendor.evoplay.isbalancedincreasetestenabled=false

image.gameurl=https://exampleValue

spring.kafka.properties.bootstrap.servers=exampleValue
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='exampleValue' password='exampleValue';
spring.kafka.properties.basic.auth.user.info=exampleValue:exampleValue
spring.kafka.properties.schema.registry.url=exampleValue

logging.http-request=true
logging.enable-vendor-data-flow-logs=true
logging.data-flow-logs-vendor-list=1,4,19
testing.stub=false

spring.jpa.show.sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.maria-dialect=org.hibernate.dialect.MariaDBDialect

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

aws.s3.id=exampleValue
aws.s3.secret=exampleValue
aws.s3.bucket=gameurl
aws.s3.region=exampleValue
aws.s3.folder=qa
aws.s3.gameUrl=https://exampleValue
aws.s3.bet-bucket=exampleValue
aws.s3.bet-bucket.write=true
aws.s3.bet-bucket.read=true

spring.datasource.game-aggregator-service-reader.jdbc-url=jdbc:mysql://exampleValue:3306/game_aggregator_qa?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
spring.datasource.game-aggregator-service-reader.username=exampleValue
spring.datasource.game-aggregator-service-reader.password=exampleValue
spring.datasource.game-aggregator-service-reader.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.wallet-service-writer.jdbc-url=jdbc:mysql://exampleValue:3306/game_aggregator_wallet?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
spring.datasource.wallet-service-writer.username=exampleValue
spring.datasource.wallet-service-writer.password=exampleValue
spring.datasource.wallet-service-writer.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.wallet-service-reader.jdbc-url=jdbc:mysql://exampleValue:3306/game_aggregator_wallet?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
spring.datasource.wallet-service-reader.username=exampleValue
spring.datasource.wallet-service-reader.password=exampleValue
spring.datasource.wallet-service-reader.driver-class-name=com.mysql.cj.jdbc.Driver

walletservice.host=https://exampleValue
walletservice.timeout=10000

scheduler.bet-result-retry=true

spring.datasource.clickhouse-default.driver-class-name=ru.yandex.clickhouse.ClickHouseDriver
spring.datasource.clickhouse-default.jdbc-url=jdbc:clickhouse://exampleValue:8123/game_aggregator_qa
spring.datasource.clickhouse-default.username=exampleValue
spring.datasource.clickhouse-default.password=exampleValue
spring.datasource.clickhouse-default.idle-timeout=300000
spring.datasource.clickhouse-default.connection-timeout=20000
spring.datasource.clickhouse-default.maximum-pool-size=25
spring.datasource.clickhouse-default.minimum-idle=5
spring.datasource.clickhouse-default.enable=false

stdout.enabled=true
