server:
  port: 8082
  http2:
    enabled: true
mavenTimestamp: @timestamp@
sas:
  enabled: false
spring:
  application:
    name: vendor-api-service
  profiles:
    include: dev
  main:
    allow-bean-definition-overriding: true
springdoc:
  api-docs:
    path: /${spring.application.name}/v3/api-docs
  swagger-ui:
    path: /${spring.application.name}/swagger-ui.html
    tryItOutEnabled: true
  paths-to-match: /**
#logging:
#  config: classpath:logback-spring.xml
