server:
  servlet:
    context-path: /vendor
spring:
  datasource:
    hikari:
      maximum-pool-size: 100
      minimum-idle: 50
    maria-default:
      driver-class-name: org.mariadb.jdbc.Driver
      # aws rds
      jdbc-url: jdbc:mariadb://stg.c2q9vzndalx6.ap-east-1.rds.amazonaws.com:3306/game_aggregator_staging?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: user_dev
      password: Newfuture!23
  jpa:
    properties:
      hibernate:
        maria-dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: false
  couchbase:
    connectionString: couchbases://cb.mjm2txymbqasuope.cloud.couchbase.com
    userName: stg
    password: Asdf1234@
    bucketName: stg_game_aggregator
    scopeName: raw
  data:
    redis:
      mode: 
      nodehosts: 
      database: 1
      host: r-zf8hs75jbvx4wb17gjpd.redis.kualalumpur.rds.aliyuncs.com
      port: 6379
      username: dev
      password: Asdf1234-
      jedis:
        pool:
          max-idle: 30
          max-active: 100
          min-idle: 10
          max-wait: 2000
  kafka:
    properties:
      security:
        protocol: SASL_SSL
      client:
        dns:
          lookup: use_all_dns_ips
      sasl:
        mechanism: PLAIN
        jaas:
          config:
            org.apache.kafka.common.security.plain.PlainLoginModule required username='QWJ5MKVZ7UCBLT2B'
            password='exLnoeIP42pM7ZD5+1txbgOPGMfR3b2R9R1D/WdrXEeQ/rdgJaXGxzyT+mW1xr/C';
      acks: all
      bootstrap:
        servers: pkc-4v1gp.ap-northeast-1.aws.confluent.cloud:9092
      session:
        timeout:
          ms: "45000"
      basic:
        auth:
          credentials:
            source: "USER_INFO"
          user:
            info: "MM5W2HQEZEPAESML:gReou3wimJ53DV0b7ySZ7J9GDIVKgbAuy9LlBdgGkVpstaFzDgpZm5p00ZyZDCJX"
      schema:
        registry:
          url: "https://psrc-10wgj.ap-southeast-2.aws.confluent.cloud"
logging:
  config: classpath:logback-spring.xml
  http-request: true
logstash:
  host: logstash
  port: 5000
testing:
  stub: false
image:
  gameurl: https://develops-bo-s3.s3.ap-east-1.amazonaws.com
#grpc:
#  server:
#    port: 9092
#  client:
#    game-aggregator-operator-api-service:
#      address: "discovery:///operator-api"
#      enableKeepAlive: true
#      keepAliveWithoutCalls: true
#      negotiationType: plaintext
