server:
  servlet:
    context-path: /vendor
spring:
  datasource:
    hikari:
      maximum-pool-size: 100
      minimum-idle: 50
    maria-default:
      driver-class-name: org.mariadb.jdbc.Driver
      # aws rds
      jdbc-url: jdbc:mariadb://dev-2.c2q9vzndalx6.ap-east-1.rds.amazonaws.com:3306/game_aggregator_staging?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: svc_vendor_dev
      password: H2ftnFhNshRJ41
  jpa:
    properties:
      hibernate:
        maria-dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: false
  redis:
    database: 0
    host: dev.1q8pc8.ng.0001.ape1.cache.amazonaws.com
    port: 6379
    username:
    password:
    jedis:
      pool:
        min-idle: 1000
        max-idle: 1000
        max-active: 1000
        max-wait: 2000
  kafka:
    properties:
      security:
        protocol: SASL_SSL
      client:
        dns:
          lookup: use_all_dns_ips
      sasl:
        mechanism: PLAIN
        jaas:
          config:
            org.apache.kafka.common.security.plain.PlainLoginModule required username='JYE3Y3BG6AWD6JVQ'
            password='J6eK7L9IemczU6LfsFXoHmxq1Gq4mfIBmMK0Y/EOnfIIjFUMBfA5kerKR26KZdye';
      acks: all
      bootstrap:
        servers: pkc-817wq.ap-east-1.aws.confluent.cloud:9092
      session:
        timeout:
          ms: "45000"
logging:
  config: classpath:logback-spring.xml
logstash:
  host: logstash
  port: 5000
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://eureka:8761/eureka/
#   instance:
#     hostName: ga-vendor-api-service
#     preferIpAddress: false
testing:
  stub: true
#grpc:
#  server:
#    port: 9092
#  client:
#    game-aggregator-operator-api-service:
#      address: "discovery:///operator-api"
#      enableKeepAlive: true
#      keepAliveWithoutCalls: true
#      negotiationType: plaintext
