server:
  port: 8082
  http2:
    enabled: true
  tomcat:
    basedir: .. # pointing to parent folder, to be configured when deploying to server
    accesslog:
      enabled: true
    accept-count: 2500 # Maximum queue length for incoming connection requests when all possible request processing threads are in use.
    max-connections: 16384 # Default: 8192 (Maximum number of connections that the server accepts and processes at any given time.)
#    max-threads: 4000
#    min-spare-threads: 4000
    threads:
      min-spare: 100  # Default: 10 (Minimum amount of worker threads.)
      max: 100        # Default: 200 (Maximum amount of worker threads.)

mavenTimestamp: @timestamp@
sas:
  enabled: false
spring:
  application:
    name: vendor-api-service
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
springdoc:
  api-docs:
    path: /${spring.application.name}/v3/api-docs
  swagger-ui:
    path: /${spring.application.name}/swagger-ui.html
    tryItOutEnabled: true
  paths-to-match: /**
