server:
  port: 8082
  http2:
    enabled: true
  tomcat:
    accept-count: 1000 # Maximum queue length for incoming connection requests when all possible request processing threads are in use.
    max-connections: 10000 # Maximum number of connections that the server accepts and processes at any given time.
    max-threads: 500 # Maximum amount of worker threads.
    min-spare-threads: 50 # Minimum amount of worker threads.
    accesslog:
      enabled: true
    basedir: .. # pointing to parent folder, to be configured when deploying to server

mavenTimestamp: @timestamp@
sas:
  enabled: false
spring:
  application:
    name: vendor-api-service
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
springdoc:
  api-docs:
    path: /${spring.application.name}/v3/api-docs
  swagger-ui:
    path: /${spring.application.name}/swagger-ui.html
    tryItOutEnabled: true
  paths-to-match: /**
#logging:
#  config: classpath:logback-spring.xml
