spring:
  liquibase:
    enabled: false
  datasource:
    hikari:
      maximum-pool-size: 100
      minimum-idle: 50
    maria-default:
      driver-class-name: org.mariadb.jdbc.Driver
      # ali rds
      jdbc-url: jdbc:mariadb://rm-gs5ghwkvepn004p4k1o.mariadb.singapore.rds.aliyuncs.com:3306/game_aggregator_staging?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: ga_admin
      password: Asdf1234-
#      jdbc-url: jdbc:mariadb://127.0.0.1:3309/game_aggregator_local?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#      username: root
#      password: password
  jpa:
    properties:
      hibernate:
        maria-dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: false
  couchbase:
    connectionString: couchbases://cb.mjm2txymbqasuope.cloud.couchbase.com
    userName: dev
    password: Asdf1234@
    bucketName: qa_game_aggregator
    scopeName: raw
  data:
    redis:
      mode: 
      nodehosts: 
      database: 0
      host: r-zf8hs75jbvx4wb17gjpd.redis.kualalumpur.rds.aliyuncs.com
      port: 6379
      username: dev
      password: Asdf1234-
      jedis:
        pool:
          max-idle: 30
          max-active: 100
          min-idle: 10
          max-wait: 2000
  kafka:
    properties:
      security:
        protocol: SASL_SSL
      client:
        dns:
          lookup: use_all_dns_ips
      sasl:
        mechanism: PLAIN
        jaas:
          config:
            org.apache.kafka.common.security.plain.PlainLoginModule required username='JYE3Y3BG6AWD6JVQ'
            password='J6eK7L9IemczU6LfsFXoHmxq1Gq4mfIBmMK0Y/EOnfIIjFUMBfA5kerKR26KZdye';
      acks: all
      bootstrap:
        servers: pkc-817wq.ap-east-1.aws.confluent.cloud:9092
      session:
        timeout:
          ms: "45000"
      basic:
        auth:
          credentials:
            source: "USER_INFO"
          user:
            info: "VSUSBSIXSWS77SLP:y8DquVxz9PVCrVM91JG2QlG7hsvzq7j0ijiRAqw/ebDtv88cL3afcm7PZnCBODJ4"
      schema:
        registry:
          url: "https://psrc-l6oz3.us-east-2.aws.confluent.cloud"
logging:
  http-request: true
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
  config: classpath:logback-spring.xml
logstash:
  host: 8.210.47.56
  port: 5000
testing:
  stub: false


image:
  gameurl: https://develops-bo-s3.s3.ap-east-1.amazonaws.com
#logstash:
#  address: "127.0.0.1:5000"

# Micro-services list
#grpc:
#  server:
#    port: 9092
#  client:
#    game-aggregator-operator-api-service:
#      address: 'static://localhost:9093'
#      enableKeepAlive: true
#      keepAliveWithoutCalls: true
#      negotiationType: plaintext
