spring:
  datasource:
    maria-default:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://rm-gs5ghwkvepn004p4k1o.mariadb.singapore.rds.aliyuncs.com:3306/game_aggregator_staging?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: ga_admin
      password: Asdf1234-
    maria-reader:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://rm-gs5ghwkvepn004p4k1o.mariadb.singapore.rds.aliyuncs.com:3306/game_aggregator_qa?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: ga_admin
      password: Asdf1234-
    maria-writer:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://rm-gs5ghwkvepn004p4k1o.mariadb.singapore.rds.aliyuncs.com:3306/game_aggregator_qa?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: ga_admin
      password: Asdf1234-
  liquibase:
    change-log: /liquibase/master.xml
  jpa:
    properties:
      hibernate:
        maria-dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: false
  redis:
    host: r-zf8hs75jbvx4wb17gjpd.redis.kualalumpur.rds.aliyuncs.com
    port: 6379
    username: dev
    password: Asdf1234-
    jedis:
      pool:
        max-idle: 30
        max-active: 100
        min-idle: 10
        max-wait: 2000
  kafka:
    properties:
      security:
        protocol: SASL_SSL
      client:
        dns:
          lookup: use_all_dns_ips
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='JYE3Y3BG6AWD6JVQ'
            password='J6eK7L9IemczU6LfsFXoHmxq1Gq4mfIBmMK0Y/EOnfIIjFUMBfA5kerKR26KZdye';
      acks: all
      bootstrap:
        servers: pkc-817wq.ap-east-1.aws.confluent.cloud:9092
      session:
        timeout:
          ms: '45000'
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
grpc:
  server:
    port: 9092
  client:
    game-aggregator-operator-api-service:
      address: 'static://ga-operator-api-service:9093'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
