package com.nextgen.gameaggregator.core.engine.wallet.bet;

import lombok.Builder;
import lombok.Data;

import java.math.BigDecimal;

/**
 * Represents the context and details of a single betting transaction.
 * <p>
 * This class encapsulates all necessary information required to process a bet,
 * including details provided by the vendor, the player, the game, and internal
 * values for tracking and processing. It serves as a central data container
 * for bet-related operations across different services.
 */
@Data
@Builder
public class BetContext {
    /**
     * A unique key used to prevent duplicate transaction processing.
     * This key should be generated by the vendor and ensure
     * that the same bet request is not processed multiple times.
     */
    private String idempotencyKey;

    /**
     * The username of the player as provided by the vendor.
     * This is the identifier used by the external betting system.
     */
    private String vendorPlayerUsername;

    /**
     * The unique code identifying the game for which the bet is placed.
     * E.g., "SLOT001", "ROULETTE_EU".
     */
    private String gameCode;

    /**
     * The unique identifier for the current game round.
     * This helps group related transactions within a single game round.
     */
    private String roundId;

    /**
     * The unique identifier for this specific bet as provided by the vendor.
     * Used for reconciliation and tracking with the external system.
     */
    private String vendorBetId;

    /**
     * The currency code of the bet amount as provided by the vendor (e.g., "USD", "EUR").
     * This may differ from the internal {@link #currencyCode} if currency conversion occurs.
     */
    private String vendorCurrency;

    /**
     * The amount of money placed as a bet.
     * This value is typically positive.
     */
    private BigDecimal betAmount;

    /**
     * The session token provided by the vendor, confirming the player's active session.
     * Used for validating the authenticity of the bet request.
     */
    private String vendorSessionToken;

    /**
     * The timestamp when the bet was initiated by the vendor, in milliseconds since the Unix epoch.
     */
    private Long timestamp;

    // --- internal values ---

    /**
     * A unique identifier for tracing requests across distributed services.
     * Used for debugging and logging to follow the lifecycle of a bet transaction.
     */
    private String traceId;

    private String vendorClassName;
    private Integer vendorId;
    private Long vendorPlayerId;
    private Integer agentId;
    private Long agentPlayerId;

    /**
     * The username of the player as known within the agent's system.
     * Populated automatically by Core Engine
     */
    private String agentPlayerUsername;
    private String currencyCode;
    private String externalTransactionId;
    private String betId;
}
